### ISSUE TITLE
Checkstyle's html report related links are not working

### ISSUE THREAD

**Issue by ashishrana160796** [checkstyle/checkstyle.github.io#3]
`Checkstyle's html report for Guava library`(https://checkstyle.org/reports/google-style/guava/) link on the following page, https://checkstyle.org/google_style.html
`Checkstyle's html report for Open JDK library (javadoc validation)`(https://checkstyle.org/reports/javadoc/openjdk8/) link on the following page, 
https://checkstyle.org/sun_style.html

are not working(`404 Error`).

**Comment by romani** [comment]
While we are looking at problem , please use our sourseforge web site. Migration to new domain was not completely finished

**Comment by romani** [comment]
Relative path need to changed to absolute (to sourseforge)

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/sun_style.xml#L30

https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/google_style.xml#L31

**Comment by romani** [comment]
Issue is moved to main repository issue tracker
